name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Generate Coverage Badge
        run: |
          if [ -f coverage/coverage-summary.json ]; then
            npx istanbul-badges-readme --coverageDir=coverage --outputDir=coverage/badge
          else
            echo "Coverage summary not found, skipping badge generation."
            exit 1
          fi

      - name: Upload Coverage Badge
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-badge
          path: coverage/badge/badge.svg
